namespace Nikse.SubtitleEdit.Features.Video.TextToSpeech.Engines;

// Auto-generated from omnivoice.cpp/src/lang-map.h (646 entries).
// omnivoice-tts accepts either the ISO ID (the second column) or the
// English language name (case-insensitive). We send the ISO ID so the
// command-line stays compact and locale-independent.
internal static class OmniVoiceLanguages
{
    public static readonly TtsLanguage[] All = new TtsLanguage[]
    {
        new("Abadi", "kbt"),
        new("Abkhazian", "ab"),
        new("Abron", "abr"),
        new("Abua", "abn"),
        new("Adamawa Fulfulde", "fub"),
        new("Adyghe", "ady"),
        new("Afade", "aal"),
        new("Afrikaans", "af"),
        new("Agwagwune", "yay"),
        new("Aja (Benin)", "ajg"),
        new("Akebu", "keu"),
        new("Alago", "ala"),
        new("Albanian", "sq"),
        new("Algerian Arabic", "arq"),
        new("Algerian Saharan Arabic", "aao"),
        new("Ambo-Pasco Quechua", "qva"),
        new("Ambonese Malay", "abs"),
        new("Amdo Tibetan", "adx"),
        new("Amharic", "am"),
        new("Anaang", "anw"),
        new("Angika", "anp"),
        new("Antankarana Malagasy", "xmv"),
        new("Aragonese", "an"),
        new("Arbëreshë Albanian", "aae"),
        new("Arequipa-La Unión Quechua", "qxu"),
        new("Armenian", "hy"),
        new("Ashe", "ahs"),
        new("Ashéninka Perené", "prq"),
        new("Askopan", "eiv"),
        new("Assamese", "as"),
        new("Asturian", "ast"),
        new("Atayal", "tay"),
        new("Awak", "awo"),
        new("Ayacucho Quechua", "quy"),
        new("Azerbaijani", "az"),
        new("Baatonum", "bba"),
        new("Bacama", "bcy"),
        new("Bade", "bde"),
        new("Bafia", "ksf"),
        new("Bafut", "bfd"),
        new("Bagirmi Fulfulde", "fui"),
        new("Bago-Kusuntu", "bqg"),
        new("Baharna Arabic", "abv"),
        new("Bakoko", "bkh"),
        new("Balanta-Ganja", "bjt"),
        new("Balti", "bft"),
        new("Bamenyam", "bce"),
        new("Bamun", "bax"),
        new("Bangwinji", "bsj"),
        new("Banjar", "bjn"),
        new("Bankon", "abb"),
        new("Baoulé", "bci"),
        new("Bara Malagasy", "bhr"),
        new("Barok", "bjk"),
        new("Basa (Cameroon)", "bas"),
        new("Basa (Nigeria)", "bzw"),
        new("Bashkir", "ba"),
        new("Basque", "eu"),
        new("Batak Mandailing", "btm"),
        new("Batanga", "bnm"),
        new("Bateri", "btv"),
        new("Bats", "bbl"),
        new("Bayot", "bda"),
        new("Bebele", "beb"),
        new("Belarusian", "be"),
        new("Bengali", "bn"),
        new("Betawi", "bew"),
        new("Bhili", "bhb"),
        new("Bhojpuri", "bho"),
        new("Bilur", "bxf"),
        new("Bima", "bhp"),
        new("Bodo", "brx"),
        new("Boghom", "bux"),
        new("Bokyi", "bky"),
        new("Bomu", "bmq"),
        new("Bondei", "bou"),
        new("Borgu Fulfulde", "fue"),
        new("Bosnian", "bs"),
        new("Brahui", "brh"),
        new("Braj", "bra"),
        new("Breton", "br"),
        new("Buduma", "bdm"),
        new("Buginese", "bug"),
        new("Bukharic", "bhh"),
        new("Bulgarian", "bg"),
        new("Bulu (Cameroon)", "bum"),
        new("Bundeli", "bns"),
        new("Bunun", "bnn"),
        new("Bura-Pabir", "bwr"),
        new("Burak", "bys"),
        new("Burmese", "my"),
        new("Burushaski", "bsk"),
        new("Cacaloxtepec Mixtec", "miu"),
        new("Cajatambo North Lima Quechua", "qvl"),
        new("Cakfem-Mushere", "cky"),
        new("Cameroon Pidgin", "wes"),
        new("Campidanese Sardinian", "sro"),
        new("Cantonese", "yue"),
        new("Catalan", "ca"),
        new("Cebuano", "ceb"),
        new("Cen", "cen"),
        new("Central Kurdish", "ckb"),
        new("Central Nahuatl", "nhn"),
        new("Central Pame", "pbs"),
        new("Central Pashto", "pst"),
        new("Central Puebla Nahuatl", "ncx"),
        new("Central Tarahumara", "tar"),
        new("Central Yupik", "esu"),
        new("Central-Eastern Niger Fulfulde", "fuq"),
        new("Chadian Arabic", "shu"),
        new("Chichewa", "ny"),
        new("Chichicapan Zapotec", "zpv"),
        new("Chiga", "cgg"),
        new("Chimalapa Zoque", "zoh"),
        new("Chimborazo Highland Quichua", "qug"),
        new("Chinese", "zh"),
        new("Chiquián Ancash Quechua", "qxa"),
        new("Chitwania Tharu", "the"),
        new("Chokwe", "cjk"),
        new("Chuvash", "cv"),
        new("Cibak", "ckl"),
        new("Coastal Konjo", "kjc"),
        new("Copainalá Zoque", "zoc"),
        new("Cornish", "kw"),
        new("Corongo Ancash Quechua", "qwa"),
        new("Croatian", "hr"),
        new("Cross River Mbembe", "mfn"),
        new("Cuyamecalco Mixtec", "xtu"),
        new("Czech", "cs"),
        new("Dadiya", "dbd"),
        new("Dagbani", "dag"),
        new("Dameli", "dml"),
        new("Danish", "da"),
        new("Dargwa", "dar"),
        new("Dazaga", "dzg"),
        new("Deccan", "dcc"),
        new("Degema", "deg"),
        new("Dera (Nigeria)", "kna"),
        new("Dghwede", "dgh"),
        new("Dhatki", "mki"),
        new("Dhivehi", "dv"),
        new("Dhofari Arabic", "adf"),
        new("Dijim-Bwilim", "cfa"),
        new("Dogri", "dgo"),
        new("Domaaki", "dmk"),
        new("Dotyali", "dty"),
        new("Duala", "dua"),
        new("Dutch", "nl"),
        new("Dũya", "ldb"),
        new("Dyula", "dyu"),
        new("Eastern Balochi", "bgp"),
        new("Eastern Bolivian Guaraní", "gui"),
        new("Eastern Egyptian Bedawi Arabic", "avl"),
        new("Eastern Krahn", "kqo"),
        new("Eastern Mari", "mhr"),
        new("Eastern Yiddish", "ydd"),
        new("Ebrié", "ebr"),
        new("Eggon", "ego"),
        new("Egyptian Arabic", "arz"),
        new("Ejagham", "etu"),
        new("Eleme", "elm"),
        new("Eloyi", "afo"),
        new("Embu", "ebu"),
        new("English", "en"),
        new("Erzya", "myv"),
        new("Esan", "ish"),
        new("Esperanto", "eo"),
        new("Estonian", "et"),
        new("Eton (Cameroon)", "eto"),
        new("Ewondo", "ewo"),
        new("Extremaduran", "ext"),
        new("Fang (Equatorial Guinea)", "fan"),
        new("Fanti", "fat"),
        new("Farefare", "gur"),
        new("Fe'fe'", "fmp"),
        new("Filipino", "fil"),
        new("Filomena Mata-Coahuitlán Totonac", "tlp"),
        new("Finnish", "fi"),
        new("Fipa", "fip"),
        new("French", "fr"),
        new("Fulah", "ff"),
        new("Galician", "gl"),
        new("Gambian Wolof", "wof"),
        new("Ganda", "lg"),
        new("Garhwali", "gbm"),
        new("Gawar-Bati", "gwt"),
        new("Gawri", "gwc"),
        new("Gbagyi", "gbr"),
        new("Gbari", "gby"),
        new("Geji", "gyz"),
        new("Gen", "gej"),
        new("Georgian", "ka"),
        new("German", "de"),
        new("Geser-Gorom", "ges"),
        new("Gheg Albanian", "aln"),
        new("Ghomálá'", "bbj"),
        new("Gidar", "gid"),
        new("Glavda", "glw"),
        new("Goan Konkani", "gom"),
        new("Goaria", "gig"),
        new("Goemai", "ank"),
        new("Gola", "gol"),
        new("Greek", "el"),
        new("Guarani", "gn"),
        new("Guduf-Gava", "gdf"),
        new("Guerrero Amuzgo", "amu"),
        new("Gujarati", "gu"),
        new("Gujari", "gju"),
        new("Gulf Arabic", "afb"),
        new("Gurgula", "ggg"),
        new("Gusii", "guz"),
        new("Gusilay", "gsl"),
        new("Gweno", "gwe"),
        new("Güilá Zapotec", "ztu"),
        new("Hadothi", "hoj"),
        new("Hahon", "hah"),
        new("Haitian", "ht"),
        new("Hakha Chin", "cnh"),
        new("Hakö", "hao"),
        new("Halia", "hla"),
        new("Hausa", "ha"),
        new("Hawaiian", "haw"),
        new("Hazaragi", "haz"),
        new("Hebrew", "he"),
        new("Hemba", "hem"),
        new("Herero", "hz"),
        new("Highland Konjo", "kjk"),
        new("Hijazi Arabic", "acw"),
        new("Hindi", "hi"),
        new("Huarijio", "var"),
        new("Huautla Mazatec", "mau"),
        new("Huaxcaleca Nahuatl", "nhq"),
        new("Huba", "hbb"),
        new("Huitepec Mixtec", "mxs"),
        new("Hula", "hul"),
        new("Hungarian", "hu"),
        new("Hunjara-Kaina Ke", "hkk"),
        new("Hwana", "hwo"),
        new("Ibibio", "ibb"),
        new("Icelandic", "is"),
        new("Idakho-Isukha-Tiriki", "ida"),
        new("Idoma", "idu"),
        new("Igbo", "ig"),
        new("Igo", "ahl"),
        new("Ikposo", "kpo"),
        new("Ikwere", "ikw"),
        new("Imbabura Highland Quichua", "qvi"),
        new("Indonesian", "id"),
        new("Indus Kohistani", "mvy"),
        new("Interlingua (International Auxiliary Language Association)", "ia"),
        new("Inupiaq", "ik"),
        new("Irish", "ga"),
        new("Iron Ossetic", "os"),
        new("Isekiri", "its"),
        new("Isoko", "iso"),
        new("Italian", "it"),
        new("Ito", "itw"),
        new("Itzá", "itz"),
        new("Ixtayutla Mixtec", "vmj"),
        new("Izon", "ijc"),
        new("Jambi Malay", "jax"),
        new("Japanese", "ja"),
        new("Jaqaru", "jqr"),
        new("Jauja Wanca Quechua", "qxw"),
        new("Jaunsari", "jns"),
        new("Javanese", "jv"),
        new("Jiba", "juo"),
        new("Jju", "kaj"),
        new("Judeo-Moroccan Arabic", "aju"),
        new("Juxtlahuaca Mixtec", "vmc"),
        new("Kabardian", "kbd"),
        new("Kabras", "lkb"),
        new("Kabuverdianu", "kea"),
        new("Kabyle", "kab"),
        new("Kachi Koli", "gjk"),
        new("Kairak", "ckr"),
        new("Kalabari", "ijn"),
        new("Kalasha", "kls"),
        new("Kalenjin", "kln"),
        new("Kalkoti", "xka"),
        new("Kamba", "kam"),
        new("Kamo", "kcq"),
        new("Kanauji", "bjj"),
        new("Kanembu", "kbl"),
        new("Kannada", "kn"),
        new("Karekare", "kai"),
        new("Kashmiri", "ks"),
        new("Kathoriya Tharu", "tkt"),
        new("Kati", "bsh"),
        new("Kazakh", "kk"),
        new("Keiyo", "eyo"),
        new("Khams Tibetan", "khg"),
        new("Khana", "ogo"),
        new("Khetrani", "xhe"),
        new("Khmer", "km"),
        new("Khowar", "khw"),
        new("Kinga", "zga"),
        new("Kinnauri", "kfk"),
        new("Kinyarwanda", "rw"),
        new("Kirghiz", "ky"),
        new("Kirya-Konzəl", "fkk"),
        new("Kochila Tharu", "thq"),
        new("Kohistani Shina", "plk"),
        new("Kohumono", "bcs"),
        new("Kok Borok", "trp"),
        new("Kol (Papua New Guinea)", "kol"),
        new("Kom (Cameroon)", "bkm"),
        new("Koma", "kmy"),
        new("Konkani", "knn"),
        new("Konzo", "koo"),
        new("Korean", "ko"),
        new("Korwa", "kfp"),
        new("Kota (India)", "kfe"),
        new("Koti", "eko"),
        new("Kuanua", "ksd"),
        new("Kuanyama", "kj"),
        new("Kui (India)", "uki"),
        new("Kulung (Nigeria)", "bbu"),
        new("Kuot", "kto"),
        new("Kushi", "kuh"),
        new("Kwambi", "kwm"),
        new("Kwasio", "nmg"),
        new("Lala-Roba", "lla"),
        new("Lamang", "hia"),
        new("Lao", "lo"),
        new("Larike-Wakasihu", "alo"),
        new("Lasi", "lss"),
        new("Latgalian", "ltg"),
        new("Latvian", "lv"),
        new("Levantine Arabic", "apc"),
        new("Liana-Seti", "ste"),
        new("Liberia Kpelle", "xpe"),
        new("Liberian English", "lir"),
        new("Libyan Arabic", "ayl"),
        new("Ligurian", "lij"),
        new("Lijili", "mgi"),
        new("Lingala", "ln"),
        new("Lithuanian", "lt"),
        new("Loarki", "lrk"),
        new("Logooli", "rag"),
        new("Logudorese Sardinian", "src"),
        new("Loja Highland Quichua", "qvj"),
        new("Loloda", "loa"),
        new("Longuda", "lnu"),
        new("Loxicha Zapotec", "ztp"),
        new("Luba-Lulua", "lua"),
        new("Luo", "luo"),
        new("Lushai", "lus"),
        new("Luxembourgish", "lb"),
        new("Maasina Fulfulde", "ffm"),
        new("Maba (Chad)", "mde"),
        new("Macedo-Romanian", "rup"),
        new("Macedonian", "mk"),
        new("Mada (Cameroon)", "mxu"),
        new("Mafa", "maf"),
        new("Maithili", "mai"),
        new("Malay", "ms"),
        new("Malayalam", "ml"),
        new("Mali", "gcc"),
        new("Malinaltepec Me'phaa", "tcf"),
        new("Maltese", "mt"),
        new("Mandara", "tbf"),
        new("Mandjak", "mfv"),
        new("Manggarai", "mqy"),
        new("Manipuri", "mni"),
        new("Mansoanka", "msw"),
        new("Manx", "gv"),
        new("Maori", "mi"),
        new("Marathi", "mr"),
        new("Marghi Central", "mrt"),
        new("Marghi South", "mfm"),
        new("Maria (India)", "mrr"),
        new("Marwari (Pakistan)", "mve"),
        new("Masana", "mcn"),
        new("Masikoro Malagasy", "msh"),
        new("Matsés", "mcf"),
        new("Mazaltepec Zapotec", "zpy"),
        new("Mazatlán Mazatec", "vmz"),
        new("Mazatlán Mixe", "mzl"),
        new("Mbe", "mfo"),
        new("Mbo (Cameroon)", "mbo"),
        new("Mbum", "mdd"),
        new("Medumba", "byv"),
        new("Mekeo", "mek"),
        new("Meru", "mer"),
        new("Mesopotamian Arabic", "acm"),
        new("Mewari", "mtr"),
        new("Min Nan Chinese", "nan"),
        new("Mingrelian", "xmf"),
        new("Mitlatongo Mixtec", "vmm"),
        new("Miya", "mkf"),
        new("Mokpwe", "bri"),
        new("Moksha", "mdf"),
        new("Mom Jango", "ver"),
        new("Mongolian", "mn"),
        new("Moroccan Arabic", "ary"),
        new("Motu", "meu"),
        new("Mpiemo", "mcx"),
        new("Mpumpong", "mgg"),
        new("Mundang", "mua"),
        new("Mungaka", "mhk"),
        new("Musey", "mse"),
        new("Musgu", "mug"),
        new("Musi", "mui"),
        new("Naba", "mne"),
        new("Najdi Arabic", "ars"),
        new("Nalik", "nal"),
        new("Nawdm", "nmz"),
        new("Ndonga", "ng"),
        new("Neapolitan", "nap"),
        new("Nepali", "npi"),
        new("Ngamo", "nbh"),
        new("Ngas", "anc"),
        new("Ngiemboon", "nnh"),
        new("Ngizim", "ngi"),
        new("Ngomba", "jgo"),
        new("Ngombale", "nla"),
        new("Nigerian Fulfulde", "fuv"),
        new("Nigerian Pidgin", "pcm"),
        new("Nimadi", "noe"),
        new("Nobiin", "fia"),
        new("North Mesopotamian Arabic", "ayp"),
        new("North Moluccan Malay", "max"),
        new("Northern Betsimisaraka Malagasy", "bmm"),
        new("Northern Hindko", "hno"),
        new("Northern Kurdish", "kmr"),
        new("Northern Pame", "pmq"),
        new("Northern Pashto", "pbu"),
        new("Northern Uzbek", "uzn"),
        new("Northwest Gbaya", "gya"),
        new("Norwegian", "no"),
        new("Norwegian Bokmål", "nb"),
        new("Norwegian Nynorsk", "nn"),
        new("Notsi", "ncf"),
        new("Nyankpa", "yes"),
        new("Nyungwe", "nyu"),
        new("Nzanyi", "nja"),
        new("Nüpode Huitoto", "hux"),
        new("Occitan", "oc"),
        new("Od", "odk"),
        new("Odia", "ory"),
        new("Odual", "odu"),
        new("Omani Arabic", "acx"),
        new("Orizaba Nahuatl", "nlv"),
        new("Orma", "orc"),
        new("Ormuri", "oru"),
        new("Oromo", "om"),
        new("Pahari-Potwari", "phr"),
        new("Paiwan", "pwn"),
        new("Panjabi", "pa"),
        new("Papuan Malay", "pmy"),
        new("Parkari Koli", "kvx"),
        new("Pedi", "nso"),
        new("Pero", "pip"),
        new("Persian", "fa"),
        new("Petats", "pex"),
        new("Phalura", "phl"),
        new("Piemontese", "pms"),
        new("Piya-Kwonci", "piy"),
        new("Plateau Malagasy", "plt"),
        new("Polish", "pl"),
        new("Poqomam", "poc"),
        new("Portuguese", "pt"),
        new("Pulaar", "fuc"),
        new("Pular", "fuf"),
        new("Puno Quechua", "qxp"),
        new("Pushto", "ps"),
        new("Pökoot", "pko"),
        new("Qaqet", "byx"),
        new("Quiotepec Chinantec", "chq"),
        new("Rana Tharu", "thr"),
        new("Rangi", "lag"),
        new("Rapoisi", "kyx"),
        new("Ratahan", "rth"),
        new("Rayón Zoque", "zor"),
        new("Romanian", "ro"),
        new("Romansh", "rm"),
        new("Rombo", "rof"),
        new("Rotokas", "roo"),
        new("Rukai", "dru"),
        new("Russian", "ru"),
        new("Sacapulteco", "quv"),
        new("Saidi Arabic", "aec"),
        new("Sakalava Malagasy", "skg"),
        new("Sakizaya", "szy"),
        new("Saleman", "sau"),
        new("Samba Daka", "ccg"),
        new("Samba Leko", "ndi"),
        new("San Felipe Otlaltepec Popoloca", "pow"),
        new("San Francisco Del Mar Huave", "hue"),
        new("San Juan Atzingo Popoloca", "poe"),
        new("San Martín Itunyoso Triqui", "trq"),
        new("San Miguel El Grande Mixtec", "mig"),
        new("Sansi", "ssi"),
        new("Sanskrit", "sa"),
        new("Santa Ana De Tusi Pasco Quechua", "qxt"),
        new("Santa Catarina Albarradas Zapotec", "ztn"),
        new("Santali", "sat"),
        new("Santiago Del Estero Quichua", "qus"),
        new("Saposa", "sps"),
        new("Saraiki", "skr"),
        new("Sardinian", "sc"),
        new("Saya", "say"),
        new("Sediq", "trv"),
        new("Serbian", "sr"),
        new("Seri", "sei"),
        new("Shina", "scl"),
        new("Shona", "sn"),
        new("Siar-Lak", "sjr"),
        new("Sibe", "nco"),
        new("Sicilian", "scn"),
        new("Sihuas Ancash Quechua", "qws"),
        new("Sikkimese", "sip"),
        new("Sinaugoro", "snc"),
        new("Sindhi", "sd"),
        new("Sindhi Bhil", "sbn"),
        new("Sinhala", "si"),
        new("Sinicahua Mixtec", "xti"),
        new("Sipacapense", "qum"),
        new("Siwai", "siw"),
        new("Slovak", "sk"),
        new("Slovenian", "sl"),
        new("Solos", "sol"),
        new("Somali", "so"),
        new("Soninke", "snk"),
        new("South Giziga", "giz"),
        new("South Ucayali Ashéninka", "cpy"),
        new("Southeastern Nochixtlán Mixtec", "mxy"),
        new("Southern Betsimisaraka Malagasy", "bzc"),
        new("Southern Pashto", "pbt"),
        new("Southern Pastaza Quechua", "qup"),
        new("Soyaltepec Mazatec", "vmp"),
        new("Spanish", "es"),
        new("Standard Arabic", "arb"),
        new("Standard Moroccan Tamazight", "zgh"),
        new("Sudanese Arabic", "apd"),
        new("Sulka", "sua"),
        new("Svan", "sva"),
        new("Swahili", "sw"),
        new("Swedish", "sv"),
        new("Tae'", "rob"),
        new("Tahaggart Tamahaq", "thv"),
        new("Taita", "dav"),
        new("Tajik", "tg"),
        new("Tamil", "ta"),
        new("Tandroy-Mahafaly Malagasy", "tdx"),
        new("Tangale", "tan"),
        new("Tanosy Malagasy", "txy"),
        new("Tarok", "yer"),
        new("Tatar", "tt"),
        new("Tedaga", "tuq"),
        new("Telugu", "te"),
        new("Tem", "kdh"),
        new("Teop", "tio"),
        new("Tepeuxila Cuicatec", "cux"),
        new("Tepinapa Chinantec", "cte"),
        new("Tera", "ttr"),
        new("Terei", "buo"),
        new("Termanu", "twu"),
        new("Tesaka Malagasy", "tkg"),
        new("Tetelcingo Nahuatl", "nhg"),
        new("Teutila Cuicatec", "cut"),
        new("Thai", "th"),
        new("Tibetan", "bo"),
        new("Tidaá Mixtec", "mtx"),
        new("Tidore", "tvo"),
        new("Tigak", "tgc"),
        new("Tigre", "tig"),
        new("Tigrinya", "ti"),
        new("Tilquiapan Zapotec", "zts"),
        new("Tinputz", "tpz"),
        new("Tlacoapa Me'phaa", "tpl"),
        new("Tlacoatzintepec Chinantec", "ctl"),
        new("Tlingit", "tli"),
        new("Toki Pona", "tok"),
        new("Tomoip", "tqp"),
        new("Tondano", "tdn"),
        new("Tonsea", "txs"),
        new("Tooro", "ttj"),
        new("Torau", "ttu"),
        new("Torwali", "trw"),
        new("Tsimihety Malagasy", "xmw"),
        new("Tsotso", "lto"),
        new("Tswana", "tn"),
        new("Tugen", "tuy"),
        new("Tuki", "bag"),
        new("Tula", "tul"),
        new("Tulu", "tcy"),
        new("Tunen", "tvu"),
        new("Tungag", "lcm"),
        new("Tunisian Arabic", "aeb"),
        new("Tupuri", "tui"),
        new("Turkana", "tuv"),
        new("Turkish", "tr"),
        new("Turkmen", "tk"),
        new("Tututepec Mixtec", "mtu"),
        new("Twi", "tw"),
        new("Ubaghara", "byc"),
        new("Uighur", "ug"),
        new("Ukrainian", "uk"),
        new("Umbundu", "umb"),
        new("Upper Sorbian", "hsb"),
        new("Urdu", "ur"),
        new("Ushojo", "ush"),
        new("Uzbek", "uz"),
        new("Vai", "vai"),
        new("Vietnamese", "vi"),
        new("Votic", "vot"),
        new("Võro", "vro"),
        new("Waci Gbe", "wci"),
        new("Wadiyara Koli", "kxp"),
        new("Waja", "wja"),
        new("Wakhi", "wbl"),
        new("Wanga", "lwg"),
        new("Wapan", "juk"),
        new("Warji", "wji"),
        new("Welsh", "cy"),
        new("Wemale", "weo"),
        new("Western Frisian", "fy"),
        new("Western Highland Purepecha", "pua"),
        new("Western Juxtlahuaca Mixtec", "jmx"),
        new("Western Maninkakan", "mlq"),
        new("Western Mari", "mrj"),
        new("Western Niger Fulfulde", "fuh"),
        new("Western Panjabi", "pnb"),
        new("Wolof", "wo"),
        new("Wuzlam", "udl"),
        new("Xanaguía Zapotec", "ztg"),
        new("Xhosa", "xh"),
        new("Yace", "ekr"),
        new("Yakut", "sah"),
        new("Yalahatan", "jal"),
        new("Yanahuanca Pasco Quechua", "qur"),
        new("Yangben", "yav"),
        new("Yaqui", "yaq"),
        new("Yauyos Quechua", "qux"),
        new("Yekhee", "ets"),
        new("Yiddish", "yi"),
        new("Yidgha", "ydg"),
        new("Yoruba", "yo"),
        new("Yutanduchi Mixtec", "mab"),
        new("Zacatlán-Ahuacatlán-Tepetzintla Nahuatl", "nhi"),
        new("Zarma", "dje"),
        new("Zaza", "zza"),
        new("Zulu", "zu"),
        new("Ömie", "aom"),
    };
}

